### PR TITLE
Omit unnecessary bits when explicit conversion operators are supported

### PR DESCRIPTION
**Pull request by jeking3**
This continues #11 which continues #7.

### CODE REVIEW

**Comment by jeking3** [comment]
`safe_bool` remains for environments that do not support explicit conversion operators (thus preventing unwanted numeric conversions).  This just removes unnecessary bits when explicit conversion operators are supported in the environment and adds a test.

**Comment by Flamefire** [comment]
I wanted to post this to #7 but it was (mostly) already mentioned in #11 

Anyway:

@jeking3 could you test the following (add test cases if not existant):

```
tribool tb = boost::logic::tribool(boost::logic::indeterminate);
bool b1 = tb; // Fail for at least C++11 and up
bool b2 = static_cast<bool>(tb); // OK
int i1 = tb; // Fail
int i2 = tb + 1; // Fail
int i3 = tb << 1; // Fail
if(tb) b1 = !b1; //OK
if(tb == true) b1 = !b1; //OK
if(tb < 1) b1 = !b1; //Fail
```

Besides that this PR looks good to me. (I was one of the people against unconditional removal of safe bool which would allow int conversions)

**Comment by jeking3** [comment]
Expanding the CI build matrix found gcc-4.6 isn't handling the test re-enabled by @pdimov earlier this year, but Boost.Config claims the compiler has support.  See:

https://travis-ci.org/boostorg/logic/jobs/442138010#L1108

**Comment by eldiener** [comment]
I do not believe that any time should be spent getting versions of gcc below gcc-4.8 to work with any libraries using any c++11 features.

**Comment by pdimov** [comment]
It's either adding a BOOST_WORKAROUND here (to the condition enabling the constexpr test), or changing Config, and if we go by the path of least effort, we should choose the former.

**Comment by jeking3** [comment]
The only thing that concerns me is that in the last few days I've seen the need to add BOOST_WORKAROUND for gcc < 4.7 twice now.  Not certain why Boost.Config is claiming support for something that is pre-standard and (now provably, twice) incorrect.  I do understand changing the config macros have far wider implications however.

**Comment by pdimov** [comment]
If you want to pursue this path, the procedure would be a PR against Config, which defines the defect macro in `gcc.hpp` appropriately for 4.6 and adds to its test the failing case.

**Comment by jeking3** [comment]
Any concerns with the content here for merge?

**Comment by pdimov** [comment]
Everything looks good to me.

**Pull request merged**
